"""empty message

Revision ID: 1f161bb8297
Revises: 1f68d55ca39
Create Date: 2016-04-01 21:20:04.495577

"""

# revision identifiers, used by Alembic.
revision = '1f161bb8297'
down_revision = '1f68d55ca39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sendto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sendto_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'sender_id', 'sendto_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
