"""empty message

Revision ID: 1f68d55ca39
Revises: None
Create Date: 2016-04-01 21:14:01.930840

"""

# revision identifiers, used by Alembic.
revision = '1f68d55ca39'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
