"""empty message

Revision ID: 2f484570ea3
Revises: b66b5bc46f
Create Date: 2016-03-31 10:01:43.071388

"""

# revision identifiers, used by Alembic.
revision = '2f484570ea3'
down_revision = 'b66b5bc46f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
