"""empty message

Revision ID: 36324861aa8d
Revises: None
Create Date: 2016-04-10 09:44:55.422000

"""

# revision identifiers, used by Alembic.
revision = '36324861aa8d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('sendto_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'sendto_id')
    ### end Alembic commands ###
