"""empty message

Revision ID: 3637c58b8df
Revises: 5a800f7b902
Create Date: 2016-04-02 14:50:52.167655

"""

# revision identifiers, used by Alembic.
revision = '3637c58b8df'
down_revision = '5a800f7b902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
