"""empty message

Revision ID: 4d9cb1ac9b40
Revises: None
Create Date: 2016-04-10 10:51:41.327072

"""

# revision identifiers, used by Alembic.
revision = '4d9cb1ac9b40'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('sendto_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'sendto_id')
    ### end Alembic commands ###
