"""empty message

Revision ID: 5a1abb2bceb
Revises: 2f484570ea3
Create Date: 2016-03-31 11:22:31.448763

"""

# revision identifiers, used by Alembic.
revision = '5a1abb2bceb'
down_revision = '2f484570ea3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
