"""empty message

Revision ID: b66b5bc46f
Revises: b485991aee
Create Date: 2016-03-31 09:59:24.721610

"""

# revision identifiers, used by Alembic.
revision = 'b66b5bc46f'
down_revision = 'b485991aee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
